### ISSUE TITLE
Code: 194, e.displayText() = DB::Exception: Invalid authentication: it is not allowed to use X-ClickHouse HTTP headers and other authentication methods simultaneously (version 20.3.9.70 (official build))

### ISSUE THREAD

**Issue by vumdao** [sqlpad/sqlpad#915]
Got this error when trying to create connection to clickhouse-server

![2020-12-01_14-00](https://user-images.githubusercontent.com/37215642/100707855-ef450900-33dd-11eb-8e4f-1aac2a6525df.png)

**Comment by rickbergfalk** [comment]
Thanks for reporting @vumdao. will take a look at this shortly.

**Comment by dengc367** [comment]
test success in clickhouse with the PR #917.

![image](https://user-images.githubusercontent.com/1353036/100895862-f876c880-34f8-11eb-8c49-cc1cb5e4ee63.png)

**Comment by rickbergfalk** [comment]
@vumdao this should be fixed in `latest` docker image and next tagged SQLPad release

**Comment by vumdao** [comment]
@rickbergfalk 
The connection to clickhouse is created successfully but showing nothing on dashboard
![image](https://user-images.githubusercontent.com/37215642/100964214-b67e6e80-355a-11eb-8e8f-d0fada4cf614.png)

![image](https://user-images.githubusercontent.com/37215642/100964144-90f16500-355a-11eb-9ebf-e344e4f8eafa.png)

**Comment by rickbergfalk** [comment]
I'll see if I can reproduce in UI. You may need to press the refresh button to refresh schema after fixing connection

**Comment by rickbergfalk** [comment]
@vumdao I confirmed that this should be working. Let me know if you see something different.

**Comment by vumdao** [comment]
@rickbergfalk My sqlpad (pull latest image today) still not show anything on the dashboard, I also try to refresh the schema but no help

My clickhouse version is 20.3.9.70

Thanks.

**Comment by dengc367** [comment]
the sqlpad clickhouse connection can support clickhouse version 20.3.9.70, I have tested successfully. you need check your clickhouse server `user.xml` configuration about authentication and authorization.

**Comment by vumdao** [comment]
@dengc367 Can you please help to show me which field need to update to overcome my issue.
As I check the user.xml there's only field to fill user and password

```
    <users>
        <!-- If user name was not specified, 'default' user is used. -->
        <default>
            <password>123456</password>
        </default>
    </users>
```

**Comment by dengc367** [comment]
@vumdao  sorry, I have just seen your reply. please look at the comment of another issue https://github.com/sqlpad/sqlpad/issues/1021#issuecomment-860400814.
